### ISSUE TITLE
🐜 Utiliser Gitlab en plus de Github 👍 👍 👍 👍

### ISSUE THREAD

**Issue by maiwann** [daktary-team/scribouilli#76]
pour 2 instances Gitlab pour l'instant, priorisées :
- Framagit.org
- Gitlab.com

## TocTocToc

- [x] Nouvel ensemble de variables d'environnements (pour Gitlab, Framagit) 

- [x] Créer pour chaque instance de GitLab une OAuth App

- [x] Écrire le endpoint /gitlab-callback et trouver comment ça marche pour de vrai

- [x] Rajouter une info dans l'url en + du accesstoken pour savoir si c'est le "protocole" github ou gitlab

## Scribouilli

- [x] Supprimer les paramètres owner et reponame dans database API
-> Avoir des options dans le constructeur à la place
- [x] Interface typée + Database API abstraite (une pour github & une pour gitlab, qui partagent les fonctions liées à git)
  - [x] Une pour GitHub
  - [x] Une pour GitLab 

- [x] Déterminer avec quel protocole on s'est connecté (à github ou gitlab)

- [x] Revoir le stockage des access token dans le localStorage
  Utiliser remember :
  - https://github.com/comptanar/comptanar.github.io/blob/main/package.json#L70
  - https://github.com/DavidBruant/remember

**Comment by Ynote** [comment]
Voici un schéma de l'architecture vers laquelle on veut aller : 

```
                              ┌─────────────────────────────────────────────────────────────┐
                              │                                                             │
                              │                                                             │
                              │                                                             │
                              │                                                             │
                              │                                                             │
                              │                                                             ├────────────────────────────────────────┐
                              │                                                             │                                        │
                              │                                                             │                                        │
                              │                      GitHub / GitLab / *                    │                                        │
                              │                                                             ◄───────────────────────────────┐        │
                              │                                                             │                               │        │
                              │                                                             │                               │        │
                              │                                                             │                               │        │
                              │          ┌─────────────────────────────────────────┐        │                               │        │
                         ┌────┤          │                                         │        │                               │        │
                         │    │          │                                         │        │                               │        │
                         │    │          │                                         │        │                               │        │
                      ┌──┼────►          │               Repo Git                  │        │                               │        │
                      │  │    │          │                                         │        │                               │        │
                      │  │    │          │                                         │        │                               │        │
                      │  │    │          │                                         │        │                               │        │
                      │  │    │          └───────────────┬─────────────────────────┘        │                               │        │
                      │  │    │                          │    ▲                             │                               │        │
                      │  │    └──────────────────────────┼────┬─────────────────────────────┘                               │        │
                      │  │                               │    │                                                             │        │
                      │  │                               │    │                                                             │        │
                      │  │                               │    │                                                             │        │
                                                         │    │                                                             │        │
     API spécifiques                                     │    │                                                             │        │
                                                         │    │                                                             │        │
(Lister les repos,      ,                  ┌─────────────┴────┴─────────────┐                                               │        │
 récupérer l'état du deploiement)          │                                │                                               │        │
                                           │                                │                             Différentes connexions aux serveurs Git
                      │  │                 │     Proxy isomorphic-git       │                                               │        │
                      │  │                 │                                │                                               │        │
                      │  │                 │                                │                                               │        │
                      │  │                 └───────────  │    ▲  ───────────┘                                               │        │
                      │  │                               │    │                                                             │        │
                      │  │       Protocole git over http │    │                                                             │        │
                      │  │                               │    │                                                             │        │
                   ┌──┴──▼───────────────────────────────┼────┼─────────────┐                                ┌──────────────┴────────▼────────────────────────────────────┐
                   │                                     │    │             │                                │                                                            │
                   │                                     │    │             │                                │                                                            │
                   │   ┌─────────────────────────────────┴────┼─────────┐   │                                │                                                            │
                   │   │                                 ▼    │         │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   ├────────────────────────────────┼─►                                                          │
                   │   │               Isomorphic-git                   │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                  IndexedDB                     │   │                                │                           Toctoctoc                        │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │ ◄─┼────────────────────────────────┼──                                                          │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                                                │   │                                │                                                            │
                   │   │                     │      ▲                   │   │                                │                                                            │
                   │   │                     │      │                   │   │                                │                                                            │
                   │   └─────────────────────┼──────┼───────────────────┘   │                                └────────────────────────────────────────────────────────────┘
                   │                         │      │                       │
                   │                         │      │                       │
                   │                         │      │                       │
                   │                         │      │                       │
                   │                         │      │                       │
                   │                         │      │                       │
                   │                         │      │                       │
                   │                         │      │                       │
                   │                         ▼      │                       │
                   │                                                        │
                   │                                                        │
                   │                                                        │
                   │                      Scribouilli                       │
                   │                                                        │
                   │                                                        │
                   └────────────────────────────────────────────────────────┘
```

**Comment by Ynote** [comment]
## Recherche OAuth GitLab

Il y a trois manières de configurer une application OAuth pour GitLab, dont deux qui nécessitent de [rafraîchir le token après 2h](https://docs.gitlab.com/ee/integration/oauth_provider.html#access-token-expiration). Celle qui ne nécessite pas de rafraîchir le token nécessite qu'on soit adminitrateurice de l'instance GitLab (cf. [les API applications](https://docs.gitlab.com/ee/api/applications.html)). Ce qui sera possible pour l'instance sur Framasoft mais pas pour GitLab en général.

## Avancement
J'écris ici mon avancement principalement pour moi-même mais également pour @DavidBruant.

Pour l'instant, j'avance sans prendre le problème de rafraîchissement de token en compte. Je teste avec une application sur mon user `Ynote_hk`. Je n'arrive pas encore autoriser une application. Après m'être connectée via GitLab, j'ai une erreur lorsque j'essaie de récupérer l'`access_token`. L'erreur : 
```
{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

**Comment by DavidBruant** [comment]
Côté toctoctoc, le taf sur gitlab a commencé ici https://github.com/Scribouilli/toctoctoc/pull/12 et se poursuit par là : https://github.com/Scribouilli/toctoctoc/pull/15

Pour créer une app sur gitlab, il faut donner des permissions. Pour le moment, je crois qu'il n'y a que `read_user` et `write_repository`

- [ ] documenter les permissions à donner à une app gitlab

**Comment by Ynote** [comment]
## Déploiement d'un site Scribouilli

### Comment ça marche actuellement

Aujourd'hui, on utilise la fonctionnalité [GitHub Pages](https://pages.github.com/) qui s'active dans les settings d'un repo. C'est fait tout automatiquement grâce à GitHub avec plusieurs gem qui se coordonnent avec Jekyll, entre-autres [jekyll-remote-theme](https://github.com/benbalter/jekyll-remote-theme/tree/master/lib/jekyll-remote-theme), [pages-gem](https://github.com/github/pages-gem).

### Pour que ça marche avec GitLab

On a trois choses à gérer : 
- la possibilité de mettre un thème qui se trouve sur un repo distant (ce qui permet aux sites Scribouilli de se mettre à jour avec ce thème automatiquement à chaque déploiement)
- la gestion du déploiement dans GitLab avec `.gitlab-ci.yml`
- En utilisant un thème qui se trouve sur un repo distant, on ne peut plus utiliser la manière de faire actuelle avec les GitHub Pages (qui constraint par exemple les gems qu'on a le droit d'installer). On doit utiliser les GitHub Actions.

### Proposition pour avancer

Dans le repo `site-template` : 
- [x] Configurer Jekyll avec un thème qu'on aura déclaré dans le `Gemfile` avec un chemin vers le repo git. Voici un exemple [pour déclarer la gem](https://github.com/Ynote/test-site-template/blob/main/Gemfile#L6) et [mettre à jour la config](https://github.com/Ynote/test-site-template/blob/main/_config.yml#L4)
- [x] Écrire le build et le deploy d'un site statique Jekyll dans un `yml`. Exemples pour [GitLab](https://github.com/Ynote/test-site-template/blob/main/.gitlab-ci.yml) et [GitHub](https://github.com/Ynote/test-site-template/blob/main/.github/workflows/build-and-deploy.yml)
- [x] ~Ajouter la mention `layout: page` sur les pages d'exemple (je ne sais pas pourquoi, mais sans ça, Jekyll ne prend pas en compte les layouts du thème)~ cf ce [commentaire](https://github.com/Scribouilli/scribouilli/issues/76#issuecomment-1830604502)

Dans le repo `mimoza` : 
- [x] Ajouter un fichier `mimoza.gemspec`. cf. [exemple sur Scribougit](https://git.scribouilli.org/scribouilli/mimoza/-/blob/main/mimoza.gemspec?ref_type=heads) ou carrément utiliser le thème qui se trouve sur Scribougit.

Dans le repo `scribouilli` : 
- [x] ~Ajouter dans le front-matter des pages `layout: page` à la création d'une page~ cf ce [commentaire](https://github.com/Scribouilli/scribouilli/issues/76#issuecomment-1830604502)
- [x] ~Vérifier ce qu'il y a à faire pour les articles~ cf ce [commentaire](https://github.com/Scribouilli/scribouilli/issues/76#issuecomment-1830604502)
- [x] ~Retirer l'appel à oAuthServiceAPI.createPagesWebsiteFromRepository~

## Tester

- Vérifier qu'à la création d'un site Scribouilli sur GitHub le CI se lance bien avec les GitHub Actions et déploie une première version du site
- Idem pour GitLab quand on aura ajouté GitLab sur Scribouilli

**Comment by Ynote** [comment]
## GitLab service API

L'URL de base est `https://[GitLab origin]/api/v4/`

Je liste ici les méthodes `OAuthServiceAPI` et vérifier de quelles informations on a besoin. Je fais ce commentaire pour moi pour voir s'il y a des gros éléments bloquants avant de commencer à coder ce service.

### getAuthenticatedUser()
- Sert à remplir les champs dans le store : 
```js
{
  login: string,
  email: string,
}
```
- Endpoint possible : 
  - https://docs.gitlab.com/ee/api/users.html#list-current-user
  - `GET /user`
- Noms des champs dans l'API GitLab: `username`, `email`

Note : probablement qu'il faudra récupérer l'`id` pour faire des calls à l'API GitLab pour un user donné

### getUserEmails()


- Sert à remplir l'email principal du user dans le store
```js
{
  email: string,
}
```
- Endpoints possibles : 
  - https://docs.gitlab.com/ee/api/users.html#list-emails : ce endpoint ne permet pas de filtrer l'email principal
  - `GET /user/emails`
  - https://docs.gitlab.com/ee/api/users.html#list-current-user : on peut partir du principe que l'email associé à ce user est l'email principale ?
  - `GET /user`
- Nom du champ dans l'API GitLab: `email`

### getRepository()

- Sert à vérifier si le repo existe. On se sert de ça surtout pour lancer une erreur lorsque le repo n'existe pas.
- Endpoint : 
  - https://docs.gitlab.com/ee/api/projects.html#get-single-project
  - `GET /projects/:id`

### getCurrentUserRepositories()

- Sert à lister tous les repos publics du user qui s'est connecté par ordre de date de création décroissante. Dans le store, ça donne : 
```js
{
  reposByAccount: {
    [login: string]: {
      name: string,
      owner: string,
      publishedWebsiteURL: string, 
      repositoryURL: string
    }
  }
*/
```

- Endpoint : 
  - https://docs.gitlab.com/ee/api/projects.html#list-user-projects
  - `GET /users/:user_id/projects?visibility=public&order_by=updated_at&sort=desc`
  - ou https://docs.gitlab.com/ee/api/projects.html#list-projects-a-user-has-contributed-to 
  - `GET /users/:user_id/contributed_projects&order_by=updated_at&sort=desc`
### createDefaultRepository()

Sert à créer un repo à partir 
- Endpoint : https://docs.gitlab.com/ee/api/projects.html#create-project-for-user
- `POST /projects/user/:user_id?template_name=[name]`

Il existe deux params`use_custom_template` et `template_project_id` qu'on pourrait utiliser sur Scribougit mais ce ne sera pas possible avec une instance GitLab qu'on ne gère pas. Je propose donc qu'on parte sur le param `template_name`

### addTopicOnRepository()

À discuter de si c'est nécessaire.

### updateRepositoryFeaturesSettings()

Retire le wiki, les issues et les projects d'un repo sur GitHub. Peut-on/Doit-on faire pareil sur GitLab ? 

### createPagesWebsiteFromRepository()

Il me semble qu'on ne va pas en avoir besoin pour GitLab.

### getPagesWebsite()

Sert à récupérer le statut du déploiement d'une GitHub Pages.

- N'existe pas d'équivalent pour GitLab. Peut-être voir si on peut faire quelque chose avec leur [API sur les CI jobs](https://docs.gitlab.com/ee/api/jobs.html#get-a-single-job)

### isRepositoryReady()

Récupère un fichier du repo pour vérifier qu'il est créé

- Endpoint : https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository
- `GET /projects/:id/repository/files/_config.yml`

### callAPI()

Sert à entourer tous les appels précédents avec les bons paramètres et les bons headers.

**Comment by DavidBruant** [comment]
>  Ajouter la mention layout: page sur les pages d'exemple (je ne sais pas pourquoi, mais sans ça, Jekyll ne prend pas en compte les layouts du thème)

On n'a pas forcément besoin. On peut utiliser [jekyll-default-layout](https://rubygems.org/gems/jekyll-default-layout) qui utilise un layout par défaut (et qui est utilisé à l'intérieur de [github pages](https://github.com/github/pages-gem/blob/07c850988cd9d957b08203b52c24085b97c12516/lib/github-pages/dependencies.rb#L42) )

Et de manière générale, je pense qu'on peut aller piocher une poignée de gem un peu cool de github-pages (optional-front-matter, redirect_from, ptèt d'autres)

**Comment by DavidBruant** [comment]
>  Retirer l'appel à oAuthServiceAPI.createPagesWebsiteFromRepository

Trop cool ce morceau !
J'adore qu'on utilise mieux les plateformes et que ça nous enlève du code

**Comment by Ynote** [comment]
## Mise à jour du Gemfile

Liste des plugins à garder dans le Gemfile : 
- "jekyll-redirect-from" 
- "jekyll-sitemap"
- "jekyll-feed"
- "jekyll-paginate"
- "jekyll-seo-tag"
- "jekyll-optional-front-matter"
- "jekyll-default-layout"
- "jekyll-titles-from-headings"

Mettre à jour la version de Jekyll `4.3.2` et descendre de version si le build ne fonctionne pas.
Mettre à jour la version de ruby à `3.2.2` et descendre de version si le build ne fonctionne pas.

**Comment by Ynote** [comment]
> Retirer l'appel à oAuthServiceAPI.createPagesWebsiteFromRepository
> Trop cool ce morceau !
> J'adore qu'on utilise mieux les plateformes et que ça nous enlève du code

On va peut-être devoir garder cet appel. Je vois que dans les Settings d'un repo, il y a une option à choisir dans GitHub Pages qui s'appelle [`Build and deploy > Source > GitHub Actions`](https://github.com/Scribouilli/scribouilli/settings/pages). J'ai vu qu'on peut [passer cette option par API](https://docs.github.com/fr/rest/pages/pages?apiVersion=2022-11-28#create-a-github-pages-site) avec un argument `buildType` mis à `workflow`. 

J'ai l'impression que ça veut dire implicitement que si on ne met set pas cette information, GitHub Actions ne prendra pas en compte un déploiement sur Pages. Je vais tester sur mon repo `test-site-template` pour voir si juste avoir un fichier `.github/workflows/build-and-deploy.yml` suffit à lancer les GitHub Actions pour Pages.

**Comment by DavidBruant** [comment]
Ah ouais, bien vu
Et la source a forcément une `branch` dans l'API pour le moment https://docs.github.com/en/rest/pages/pages?apiVersion=2022-11-28#create-a-github-pages-site

**Comment by Ynote** [comment]
Par défaut, Pages est désactivé sur un repo. Sans ce call, on a cette erreur : 
```
Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action.
```

Je suis allée regarder ce paramètre `enablement`. Ça nécessite de créer un token pour pouvoir forcer l'activation des Pages via une action (et je ne suis même pas certaine d'avoir bien compris comment passer ce token à l'action). Je pense que ce sera plus simple pour nous de faire un call API comme on fait aujourd'hui, mais en ajoutant un argument `buildType: workflow`.

L'avantange en passant par les GitHub Actions, c'est qu'on n'est plus contraint d'utiliser `main` comme source principale. Les GitHub Actions expose une variable `$default-branch`. On peut mettre ça dans la config 🎉 :
```yml
on: 
  push: 
    branches: [$default-branch]
```

**Comment by Ynote** [comment]
> L'avantange en passant par les GitHub Actions, c'est qu'on n'est plus contraint d'utiliser main comme source principale. 

Je me suis avancée. Je ne suis pas sûre du call API quand même, je vais tester si ça marche sans `source` et avec `buildType: workflow`.

**Comment by Ynote** [comment]
> Je me suis avancée. Je ne suis pas sûre du call API quand même, je vais tester si ça marche sans source et avec buildType: workflow.

Je confirme que ça fonctionne.

**Comment by Ynote** [comment]
> Pour créer une app sur gitlab, il faut donner des permissions. Pour le moment, je crois qu'il n'y a que read_user et write_repository

Je rencontre un premier souci pour récupérer les repos d'un user. Contrairement à GitHub où il existe un endpoint pour récupérer les repos du user connecté, sur GitLab, on doit faire un call sur un endpoint où on passe le `username` du user : 
```
GET https://gitlab.com/api/v4/users/ynote_hk/projects?order_by=updated_at&sort=desc&per_page=30&visibility=public
```

Or, pour pouvoir appeler ce endpoint, il semble qu'on ait besoin des scopes `api` et `read_api`.

L'erreur qui m'est actuellement renvoyée, c'est : 
```json
{
  "error":"insufficient_scope",
  "error_description":"The request requires higher privileges than provided by the access token.",
  "scope":"api read_api"
}
```

**Comment by DavidBruant** [comment]
Voilà !
